Repository Natalina-Yarosh/FE57-onl, pull requests merged in 2023-12, with the labels that each got.

#1 init(hw_1): start project
  assets/images/liberty.png
  assets/style.css
  index.html
Labels: done

#3 init(hw_4): start project Axit
  .DS_Store
  img/Rectangle 111.png
  index.html
  style/style.css
Labels: done

#4 init(hw_4): start project
  image/Rectangle111.png
  index.html
  style.css
Labels: done

#11 init(hw_4): start project
  css/style.css
  img/Rectangle 111.png
  index.html
Labels: ready for code review

#8 init(hw_4): start work with Git
  Rectangle 111.png
  index.html
  style.css
Labels: done

#12 fix(hw_4): refactoring index.html and style.css
  css/style.css
  index.html
Labels: done

#7 init(hw_1): start project
  Images/image__tab.png
  index.html
  style.css
Labels: done

#5 init(hw_4): start project
  assets/images/Rectangle 111.png
  assets/style.css
  index.html
Labels: done

#9 feat(hm-4): add tabs section
  Rectangle 111.png
  index.html
  style.css
Labels: done

#15 feat(hw_5): pricing block
  index.html
  style.css
Labels: done

#6 init(hw_4): start work with Git
  index.html
  static/css/style.css
  static/img/img_liberty.png
Labels: done

#13 feat(hw_5): add pricing section
  assets/style.css
  index.html
Labels: done

#10 init(hw_4):start project
  CSS/style.css
  img/Rectangle 111.png
  index.html
Labels: done

#23 feat(hw_5): price block adding
  CSS/style.css
  index.html
Labels: done

#21 Poskrebko hw 5
  index.html
  style.css
Labels: done

#19 init(hw-4): init hw 4
  css/style.css
  img/freedom.jpg
  index.html
Labels: done

#33 Mdanilau hw 5
  assets/style.css
  index.html
Labels: done

#34 Reut hw5
  css/style.css
  index.html
Labels: done

#37 khramtsov (hw 6)
  assets/images/Cooper Dorwart.png
  assets/images/Davis Rhiel Madsen.png
  assets/images/Jaydon Rosser.png
  assets/style.css
  index.html
Labels: merged

#26 Ziaziulin (hm 5)
  css/style.css
  index.html
Labels: done

#16 Lebedev (hw_5)
  index.html
  static/css/style.css
Labels: merged

#36 feat(hw-2): add block
  CSS/style.css
  index.html
Labels: ready for code review, merged

#39 hryhoryeva (hw-6)
  image/customer-1.png
  image/customer-2.png
  image/customer-3.png
  index.html
  style.css
Labels: merged

#38 pavlov (hw 6)
  .DS_Store
  .gitignore
  assets/.DS_Store
  assets/images/avatar_cooper.png
  assets/images/avatar_devis.png
  assets/images/avatar_jaydon.png
  assets/style/style.css
  index.html
Labels: merged

#41 Lebedev (hw_6)
  index.html
  static/css/style.css
  static/img/Cooper.png
  static/img/Davis.png
  static/img/Jaydon.png
Labels: done

#49 sstnkev hm 5
  pricing.html
  style.css
Labels: ready for code review

#30 Ryabtsevich (hw4 )
  images/awesome/Group.svg
  images/awesome/bulb.png
  images/awesome/keypad.png
  images/awesome/lightning.png
  images/awesome/r_wrapper.png
  images/separator.png
  images/statue.png
  index.html
  style/styles.css
Labels: done

#44 khramtsov hw7
  assets/images/banner.jpg
  assets/images/city.jpg
  assets/style.css
  index.html
Labels: merged

#52 mdanilau (hw-6)
  assets/images/Cooper Dowart.png
  assets/images/Davis Rhiel Madsen.png
  assets/images/Jaydon Rosser.png
  assets/style.css
  index.html
Labels: merged

#51 Reut hw-6
  css/style.css
  img/1.png
  img/2.png
  img/3.png
  index.html
Labels: merged

#45 hryhoryeva hw-7
  image/background-1.png
  image/background-2.jpg
  index.html
  style.css
Labels: merged

#46 Poskrebko hw 6
  index.html
  media/Img/customers__1.png
  media/Img/customers__2.png
  media/Img/customers__3.png
  media/Img/designBG.jpg
  media/Img/facebook_icon.svg
  media/Img/github_icon.svg
  media/Img/headerBG.jpg
  media/Img/image__tab.png
  media/Img/instagram_icon.svg
  media/Img/linkedin_icon.svg
  media/Img/pinterest_icon.svg
  media/Img/rss_icon.svg
  media/Img/twitter_icon.svg
  media/style/style.css
Labels: merged

#50 feat(hw_6): customers block adding
  CSS/style.css
  img/photo 2.png
  img/photo 3.png
  img/photo1.png
  index.html
Labels: done

#56 Lebedev (hw_7)
  index.html
  static/css/style.css
  static/img/banner_background.png
  static/img/design_background.png
Labels: done, merged

#57 ukraina(hw_7): design, banner, header, footer blocks adding
  CSS/style.css
  img/Banner.jfif
  img/axure.jpg
  index.html
Labels: done

#40 Ziaziulin (hm 6)
  css/style.css
  img/customer1.png
  img/customer2.png
  img/customer3.png
  index.html
Labels: done

#67 khramtsov (hw 8)
  assets/style.css
  index.html
Labels: merged

#63 Poskrebko-hw_7
  index.html
  media/Icons/facebook_icon.svg
  media/Icons/github_icon.svg
  media/Icons/instagram_icon.svg
  media/Icons/linkedin_icon.svg
  media/Icons/logo.svg
  media/Icons/pinterest_icon.svg
  media/Icons/rss_icon.svg
  media/Icons/twitter_icon.svg
  media/style/style.css
Labels: merged
