Repository Natalina-Yarosh/FE57-onl, pull requests merged in 2024-01, with the labels that each got.

#68 hryhoryeva hw-8
  index.html
  style.css
Labels: merged

#64 mdanilau (hw-7)
  .idea/.gitignore
  .idea/Axit.iml
  .idea/modules.xml
  .idea/vcs.xml
  assets/images/city.jpg
  assets/images/street.jpg
  assets/style.css
  index.html
Labels: merged

#55 Pavlov (hw_7)
  .DS_Store
  assets/.DS_Store
  assets/images/banner.jpeg
  assets/images/image.jpg
  assets/style/style.css
  index.html
Labels: done

#81 mdanilau (hw-8)
  assets/style.css
  index.html
Labels: merged

#74 ukraina (hw-8)
  .vscode/settings.json
  CSS/style.css
  index.html
Labels: done

#70 Lebedev (hw_8)
  index.html
  static/css/style.css
Labels: done, merged

#32 Ryabtsevich (hw 5)
  index.html
  style/styles.css
Labels: done

#79 Ziaziulin (hm 7)
  css/style.css
  img/design-image.jpg
  img/promo-img.jpg
  index.html
Labels: done

#61 Ryabtsevich hw 6
  images/customers/cust1.png
  images/customers/cust2.png
  images/customers/cust3.png
  index.html
  style/styles.css
Labels: done

#62 Ryabtsevich hw 7
  images/banner/background.png
  images/design/bg-image.jpg
  index.html
  style/styles.css
Labels: done

#27 init: init homework5 + fixed blocks from previous homeworks
  css/style.css
  index.html
Labels: ready for code review

#53 Rogozhnikov hw6
  css/style.css
  img/avatars/cooper.png
  img/avatars/davis.png
  img/avatars/jaydon.png
  img/banner.png
  index.html
Labels: done

#60 Rogozhnikov hw7
  css/style.css
  img/design.jpg
  index.html
Labels: done

#77 Rogozhnikov hw 8
  css/style.css
  index.html
Labels: done

#43 Nikita visocki(hw7)
  index.html
  style1.css
Labels: need to fix

#78 Reut hw8
  css/style.css
  index.html
Labels: done

#84 Ryabtsevich hw 8
  index.html
  style/styles.css
Labels: done

#87 khramtsov (hw 9)
  assets/style.css
  index.html
Labels: merged

#92 Mansour Axit Complete
  awesome_img/01.svg
  awesome_img/02.svg
  awesome_img/03.svg
  axit.html
  customers_img/01.png
  customers_img/02.png
  customers_img/03.png
  design_img/image.jpg
  design_img/image.png
  effect_img/01.png
  icon/favicon.ico
  styles/style.css
Labels: done

#94 Ryabtsevich hw 9
  style/styles.css
Labels: done
